/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TemplatesSlugRouteImport } from './routes/templates/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TemplatesSlugIndexRouteImport } from './routes/templates/$slug/index'
import { Route as TemplatesSlugAboutRouteImport } from './routes/templates/$slug/about'
import { Route as TemplatesSlugContactRouteImport } from './routes/templates/$slug/contact'
import { Route as TemplatesSlugEventsRouteImport } from './routes/templates/$slug/events'
import { Route as TemplatesSlugGiveRouteImport } from './routes/templates/$slug/give'
import { Route as TemplatesSlugGroupsRouteImport } from './routes/templates/$slug/groups'
import { Route as TemplatesSlugLocationsRouteImport } from './routes/templates/$slug/locations'
import { Route as TemplatesSlugMinistriesRouteImport } from './routes/templates/$slug/ministries'
import { Route as TemplatesSlugNextStepsRouteImport } from './routes/templates/$slug/next-steps'
import { Route as TemplatesSlugPrayerRouteImport } from './routes/templates/$slug/prayer'
import { Route as TemplatesSlugRecoveryRouteImport } from './routes/templates/$slug/recovery'
import { Route as TemplatesSlugSermonsRouteImport } from './routes/templates/$slug/sermons'
import { Route as TemplatesSlugVisitRouteImport } from './routes/templates/$slug/visit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugIndexRoute = TemplatesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugAboutRoute = TemplatesSlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugContactRoute = TemplatesSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugEventsRoute = TemplatesSlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugGiveRoute = TemplatesSlugGiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugGroupsRoute = TemplatesSlugGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugLocationsRoute = TemplatesSlugLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugMinistriesRoute = TemplatesSlugMinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugNextStepsRoute = TemplatesSlugNextStepsRouteImport.update({
  id: '/next-steps',
  path: '/next-steps',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugPrayerRoute = TemplatesSlugPrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugRecoveryRoute = TemplatesSlugRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugSermonsRoute = TemplatesSlugSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => TemplatesSlugRoute,
} as any)
const TemplatesSlugVisitRoute = TemplatesSlugVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => TemplatesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/templates/$slug': typeof TemplatesSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$slug/about': typeof TemplatesSlugAboutRoute
  '/templates/$slug/contact': typeof TemplatesSlugContactRoute
  '/templates/$slug/events': typeof TemplatesSlugEventsRoute
  '/templates/$slug/give': typeof TemplatesSlugGiveRoute
  '/templates/$slug/groups': typeof TemplatesSlugGroupsRoute
  '/templates/$slug/locations': typeof TemplatesSlugLocationsRoute
  '/templates/$slug/ministries': typeof TemplatesSlugMinistriesRoute
  '/templates/$slug/next-steps': typeof TemplatesSlugNextStepsRoute
  '/templates/$slug/prayer': typeof TemplatesSlugPrayerRoute
  '/templates/$slug/recovery': typeof TemplatesSlugRecoveryRoute
  '/templates/$slug/sermons': typeof TemplatesSlugSermonsRoute
  '/templates/$slug/visit': typeof TemplatesSlugVisitRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$slug/about': typeof TemplatesSlugAboutRoute
  '/templates/$slug/contact': typeof TemplatesSlugContactRoute
  '/templates/$slug/events': typeof TemplatesSlugEventsRoute
  '/templates/$slug/give': typeof TemplatesSlugGiveRoute
  '/templates/$slug/groups': typeof TemplatesSlugGroupsRoute
  '/templates/$slug/locations': typeof TemplatesSlugLocationsRoute
  '/templates/$slug/ministries': typeof TemplatesSlugMinistriesRoute
  '/templates/$slug/next-steps': typeof TemplatesSlugNextStepsRoute
  '/templates/$slug/prayer': typeof TemplatesSlugPrayerRoute
  '/templates/$slug/recovery': typeof TemplatesSlugRecoveryRoute
  '/templates/$slug/sermons': typeof TemplatesSlugSermonsRoute
  '/templates/$slug/visit': typeof TemplatesSlugVisitRoute
  '/templates/$slug': typeof TemplatesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/templates/$slug': typeof TemplatesSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$slug/about': typeof TemplatesSlugAboutRoute
  '/templates/$slug/contact': typeof TemplatesSlugContactRoute
  '/templates/$slug/events': typeof TemplatesSlugEventsRoute
  '/templates/$slug/give': typeof TemplatesSlugGiveRoute
  '/templates/$slug/groups': typeof TemplatesSlugGroupsRoute
  '/templates/$slug/locations': typeof TemplatesSlugLocationsRoute
  '/templates/$slug/ministries': typeof TemplatesSlugMinistriesRoute
  '/templates/$slug/next-steps': typeof TemplatesSlugNextStepsRoute
  '/templates/$slug/prayer': typeof TemplatesSlugPrayerRoute
  '/templates/$slug/recovery': typeof TemplatesSlugRecoveryRoute
  '/templates/$slug/sermons': typeof TemplatesSlugSermonsRoute
  '/templates/$slug/visit': typeof TemplatesSlugVisitRoute
  '/templates/$slug/': typeof TemplatesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/templates/$slug'
    | '/api/auth/$'
    | '/templates/$slug/about'
    | '/templates/$slug/contact'
    | '/templates/$slug/events'
    | '/templates/$slug/give'
    | '/templates/$slug/groups'
    | '/templates/$slug/locations'
    | '/templates/$slug/ministries'
    | '/templates/$slug/next-steps'
    | '/templates/$slug/prayer'
    | '/templates/$slug/recovery'
    | '/templates/$slug/sermons'
    | '/templates/$slug/visit'
    | '/templates/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/templates/$slug/about'
    | '/templates/$slug/contact'
    | '/templates/$slug/events'
    | '/templates/$slug/give'
    | '/templates/$slug/groups'
    | '/templates/$slug/locations'
    | '/templates/$slug/ministries'
    | '/templates/$slug/next-steps'
    | '/templates/$slug/prayer'
    | '/templates/$slug/recovery'
    | '/templates/$slug/sermons'
    | '/templates/$slug/visit'
    | '/templates/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/templates/$slug'
    | '/api/auth/$'
    | '/templates/$slug/about'
    | '/templates/$slug/contact'
    | '/templates/$slug/events'
    | '/templates/$slug/give'
    | '/templates/$slug/groups'
    | '/templates/$slug/locations'
    | '/templates/$slug/ministries'
    | '/templates/$slug/next-steps'
    | '/templates/$slug/prayer'
    | '/templates/$slug/recovery'
    | '/templates/$slug/sermons'
    | '/templates/$slug/visit'
    | '/templates/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TemplatesSlugRoute: typeof TemplatesSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug/': {
      id: '/templates/$slug/'
      path: '/'
      fullPath: '/templates/$slug/'
      preLoaderRoute: typeof TemplatesSlugIndexRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/about': {
      id: '/templates/$slug/about'
      path: '/about'
      fullPath: '/templates/$slug/about'
      preLoaderRoute: typeof TemplatesSlugAboutRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/contact': {
      id: '/templates/$slug/contact'
      path: '/contact'
      fullPath: '/templates/$slug/contact'
      preLoaderRoute: typeof TemplatesSlugContactRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/events': {
      id: '/templates/$slug/events'
      path: '/events'
      fullPath: '/templates/$slug/events'
      preLoaderRoute: typeof TemplatesSlugEventsRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/give': {
      id: '/templates/$slug/give'
      path: '/give'
      fullPath: '/templates/$slug/give'
      preLoaderRoute: typeof TemplatesSlugGiveRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/groups': {
      id: '/templates/$slug/groups'
      path: '/groups'
      fullPath: '/templates/$slug/groups'
      preLoaderRoute: typeof TemplatesSlugGroupsRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/locations': {
      id: '/templates/$slug/locations'
      path: '/locations'
      fullPath: '/templates/$slug/locations'
      preLoaderRoute: typeof TemplatesSlugLocationsRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/ministries': {
      id: '/templates/$slug/ministries'
      path: '/ministries'
      fullPath: '/templates/$slug/ministries'
      preLoaderRoute: typeof TemplatesSlugMinistriesRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/next-steps': {
      id: '/templates/$slug/next-steps'
      path: '/next-steps'
      fullPath: '/templates/$slug/next-steps'
      preLoaderRoute: typeof TemplatesSlugNextStepsRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/prayer': {
      id: '/templates/$slug/prayer'
      path: '/prayer'
      fullPath: '/templates/$slug/prayer'
      preLoaderRoute: typeof TemplatesSlugPrayerRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/recovery': {
      id: '/templates/$slug/recovery'
      path: '/recovery'
      fullPath: '/templates/$slug/recovery'
      preLoaderRoute: typeof TemplatesSlugRecoveryRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/sermons': {
      id: '/templates/$slug/sermons'
      path: '/sermons'
      fullPath: '/templates/$slug/sermons'
      preLoaderRoute: typeof TemplatesSlugSermonsRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
    '/templates/$slug/visit': {
      id: '/templates/$slug/visit'
      path: '/visit'
      fullPath: '/templates/$slug/visit'
      preLoaderRoute: typeof TemplatesSlugVisitRouteImport
      parentRoute: typeof TemplatesSlugRoute
    }
  }
}

interface TemplatesSlugRouteChildren {
  TemplatesSlugAboutRoute: typeof TemplatesSlugAboutRoute
  TemplatesSlugContactRoute: typeof TemplatesSlugContactRoute
  TemplatesSlugEventsRoute: typeof TemplatesSlugEventsRoute
  TemplatesSlugGiveRoute: typeof TemplatesSlugGiveRoute
  TemplatesSlugGroupsRoute: typeof TemplatesSlugGroupsRoute
  TemplatesSlugLocationsRoute: typeof TemplatesSlugLocationsRoute
  TemplatesSlugMinistriesRoute: typeof TemplatesSlugMinistriesRoute
  TemplatesSlugNextStepsRoute: typeof TemplatesSlugNextStepsRoute
  TemplatesSlugPrayerRoute: typeof TemplatesSlugPrayerRoute
  TemplatesSlugRecoveryRoute: typeof TemplatesSlugRecoveryRoute
  TemplatesSlugSermonsRoute: typeof TemplatesSlugSermonsRoute
  TemplatesSlugVisitRoute: typeof TemplatesSlugVisitRoute
  TemplatesSlugIndexRoute: typeof TemplatesSlugIndexRoute
}

const TemplatesSlugRouteChildren: TemplatesSlugRouteChildren = {
  TemplatesSlugAboutRoute: TemplatesSlugAboutRoute,
  TemplatesSlugContactRoute: TemplatesSlugContactRoute,
  TemplatesSlugEventsRoute: TemplatesSlugEventsRoute,
  TemplatesSlugGiveRoute: TemplatesSlugGiveRoute,
  TemplatesSlugGroupsRoute: TemplatesSlugGroupsRoute,
  TemplatesSlugLocationsRoute: TemplatesSlugLocationsRoute,
  TemplatesSlugMinistriesRoute: TemplatesSlugMinistriesRoute,
  TemplatesSlugNextStepsRoute: TemplatesSlugNextStepsRoute,
  TemplatesSlugPrayerRoute: TemplatesSlugPrayerRoute,
  TemplatesSlugRecoveryRoute: TemplatesSlugRecoveryRoute,
  TemplatesSlugSermonsRoute: TemplatesSlugSermonsRoute,
  TemplatesSlugVisitRoute: TemplatesSlugVisitRoute,
  TemplatesSlugIndexRoute: TemplatesSlugIndexRoute,
}

const TemplatesSlugRouteWithChildren = TemplatesSlugRoute._addFileChildren(
  TemplatesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TemplatesSlugRoute: TemplatesSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
